package DDDTutorial_Modd;

import DDDTutorial_Modd.ConstL.ConstLatn;
import DDDTutorial_Modd.ConstL.PlAn_MAkr;

public class Pakg
{
	public static Object[] A(Object... List)
	{return List;}
	public static void Ad(ConstLatn ConstLatn)
	{
		PlAn_MAkr.MAk("Java pakag",ConstLatn,
			"Java sorc",new Object[]{
				//<editor-fold desc="com">
				A("com"
					,"esotericsoftware.reflectasm.AccessClassLoader"
					,A("sun"
						,A("jdi"
							,"ClassNotLoadedException"
							,"ClassNotPreparedException"
							/***/,"request.VMDeathRequest"
						)
						,"management.VMOption"
						,A("source"
							,"com.sun.jdi.Method"
							,"com.sun.jdi.DoubleType"
							,A("com.sun.jdi"
								,"FloatValue"
								,"Locatable"
								,"Method"
								,"Mirror"
								,"ObjectReference"
								,"PathSearchingVirtualMachine"
								,"request.BreakpointRequest"
								,"StackFrame"
								,"VirtualMachine"
							)
							,"com.sun.management.GcInfo"
							,"com.sun.net.httpserver.Authenticator.Retry"
							,A("com.sun.source"
								,A("doctree"
									,"BlockTagTree"
									,"DocTree"
									,"IndexTree"
									,"InheritDocTree"
									,"InlineTagTree"
								)
								,A("tree"
									,"AssertTree"
									,"AssignmentTree"
									,"ClassTree"
									,"CompilationUnitTree"
									,"ExpressionTree"
									,"IdentifierTree"
									,"ImportTree"
									,"ReturnTree"
									,"RequiresTree"
									,"StatementTree"
									,"Tree"
									,"TryTree"
									,"YieldTree"
								)
							)
							,A("com.sun.nio"
								,"sctp.Association"
								,A("sctp.AssociationChangeNotification"
									,"sctp.AssociationChangeNotification.AssocChangeEvent"
								)
								,"sctp.Notification"
								,"sctp.NotificationHandler"
							)
							,"com.sun.net.httpserver.Headers"
						)
					)
				)
				//</editor-fold>
				,A("java"//<editor-fold desc="java">
					,A("java.awt"
						,"AlphaComposite"
						,"BufferCapabilities"
						,"Color"
						,"color.ColorSpace"
						,"Cursor"
						,"Desktop"
						,A("desktop"
							,"AppEvent"
							,"AppForegroundListener"
							,"AppHiddenListener"
							,"SystemEventListener"
						)
						,"EventQueue"
						,"font.GlyphMetrics"
						,"Frame"
						,"geom.Point2D"
						,A("image"
							,"image"
							,"AffineTransformOp"
							/***/,"BaseMultiResolutionImage"
							,"PixelGrabber"
							,"Raster"
							,"RescaleOp"
							,"WritableRaster"
						)
						,"print.PrinterJob"
						,"RadialGradientPaint"
						,"Stroke"
						,A("AWTEvent"
							,"AWTEvent.getID"
							,"AWTEvent.initIDs"
						)
						,"event.InputEvent.isAltDown"
						,"BufferedImage"
						,"Dimension"
						,A("geom"
							,"Arc2D"
							,"Line2D"
						)
						,"Graphics"
						,"im.InputContext"
						,"OrientationRequestedType"
						,"PageAttributes"
						,"Polygon"
						,"Window"
					)
					,"java.awtTexturePaint"
					,A("java.beans"
						,"AppletInitializer"
						,"FeatureDescriptor"
						,"MethodDescriptor"
					)
					,A("java.beans"
						,"BeanProperty"
						,"JavaBean"
					)
					,A("java.io"//<editor-fold desc="">
						,"BufferedReader"
						,"CharArrayReader"
						,"Closeable"
						,"FilterInputStream"
						,"Flushable"
						,"InputStream"
						,"IOException"
						,"LineNumberInputStream"
						,"LineNumberReader"
						,"NotSerializableException"
						,"ObjectStreamException"
						,"OperationsException"
						,"Reader"
						,"Serial"
						,"Serializable"
					)//</editor-fold>
					,A("java.lang"//<editor-fold desc="">
						,A("annotation"
							,"Native.FileSystem"
							,"Retention"
							,"RetentionPolicy"
						)
						,"Appendable"
						,"ArithmeticException"
						,"AutoCloseable"
						,"BootstrapMethodError"
						,A("Class"
							,"getPrimitiveClass"
						)
						,"ClassCircularityError"
						,"ClassFormatError"
						,"ClassLoader"
						,"ClassValue"
						,"constant.DynamicCallSiteDesc"
						,"constant.MethodHandleDesc"
						,A("invoke"
							,"CallSite"
							,"MethodHandle"
							,"MethodHandleNatives"
							,"MethodHandleProxies"
							,"MethodHandles"
							,"MutableCallSite"
							,"TypeDescriptor"
						)
						,A("module"
							,"ModuleDescriptor.Requires"
							,"ResolvedModule"
							,"ResolutionException"
						)
						,"java.lang.ModuleLayer"
						,"java.lang.Process"
						,A("java.lang.instrument"
							,"java.lang.instrument.ClassDefinition"
							,"java.lang.instrument.ClassFileTransformer"
						)
						,"java.lang.Readable"
						,"java.lang.SuppressWarnings"
						,"java.lang.ThreadDeath"
						,A("java.lang.Runtime"
							,"java.lang.Runtime.ObjectMethods"
						)
						,"java.lang.ClassNotFoundException"
						,A("java.lang.management"
							,"java.lang.management.BufferPoolMXBean"
							,"java.lang.management.ClassLoadingMXBean"
						)
						,A("java.lang.invoke"
							,"java.lang.invoke.InvokerBytecodeGenerator"
							,"java.lang.invoke.InvokerBytecodeGenerator.className"
							,"java.lang.invoke.InvokerBytecodeGenerator.checkClassName"
						)
						,A("java.lang.annotation"
							,"java.lang.annotation.ElementType"
							,"java.lang.annotation.IncompleteAnnotationException"
							,"java.lang.annotation.Inherited"
							,"java.lang.annotation.Retention"
							,"java.lang.annotation.RetentionPolicy"
							,"java.lang.annotation.Target"
						)
						,"java.lang.AssertionError"
						,"java.lang.AutoCloseable"
						,"java.lang.BootstrapMethodError"
						,"java.lang.Cloneable"
						,"java.lang.CloneNotSupportedException"
						,"java.lang.Deprecated"
						,"java.lang.Error"
						,"java.lang.Exception"
						,"java.lang.FunctionalInterface"
						,"java.lang.IncompatibleClassChangeError"
						,"java.lang.InheritableThreadLocal"
						,"java.lang.invoke.TypeDescriptor.OfField"
						,"java.lang.LinkageError"
						,"java.lang.management.MemoryType"
						,"java.lang.ModuleLayer"
						,"java.lang.module.ModuleDescriptor.Provides"
						,"java.lang.Process"
						,"java.lang.ProcessBuilder"
						,"java.lang.reflect.GenericArrayType"
						,A("java.lang.reflect"
							,"java.lang.reflect.AccessibleObject"
							,"java.lang.reflect.AnnotatedArrayType"
							,"java.lang.reflect.AnnotatedElement"
							,"java.lang.reflect.Executable"
							,"java.lang.reflect.GenericDeclaration"
							,"java.lang.reflect.InvocationTargetException"
							,"java.lang.reflect.MalformedParameterizedTypeException"
							,"java.lang.reflect.MalformedParametersException"
							,"java.lang.reflect.Member"
							,"java.lang.reflect.Proxy"
						)
						,"java.lang.ReflectiveOperationException"
						,"java.lang.reflect.Type"
						,"java.lang.Runnable"
						,"java.lang.RuntimeException"
						,"java.lang.SafeVarargs"
						,"java.lang.SecurityManager"/*Finalizer attack*/
						,"java.lang.StackOverflowError"
						,"java.lang.StackWalker.StackFrame"
						,"java.lang.StringCoding"
						,"java.lang.StringConcatHelper"
						,"java.lang.System"
						,"java.lang.Thread"
						,"java.lang.ThreadLocal"
						,"java.lang.ThreadGroup"
						,"java.lang.Throwable"
						,"java.lang.UnsupportedClassVersionError"
						,"java.lang.VerifyError"
						,"java.lang.VirtualMachineError"
						,"java.lang.Void"
					)//</editor-fold>
					,A("java.math"
						,"java.math.BigDecimal"
						,"java.math.BigInteger"
					)
					,A("java.net"
						,"java.net.Authenticator.RequestorType"
						,"java.net.http.ResponseInfo"
						,A("java.net.Proxy.Type"
							,"java.net.Proxy.Type"
						)
						,"java.net.ResponseCache"
					)
					,A("java.nio"
						,"java.nio.FloatBuffer"
						,"java.nio.BufferUnderflowException"
						,A("java.nio.channels"
							,"java.nio.channels.AsynchronousCloseException"
							,"java.nio.channels.ClosedByInterruptException"
							,"java.nio.channels.FileChannel.MapMode"
							,"java.nio.channels.GatheringByteChannel"
						)
						,"java.nio.charset.MalformedInputException"
						,"java.nio.file.FileAlreadyExistsException"
					)
					,A("java.rmi"
						,"java.rmi.dgc.DGC"
						,"java.rmi.activation.ActivationGroupDesc"
						,"java.rmi.dgc.Lease"
						,"java.rmi.MarshalException"
						,A("java.rmi.registry"
							,"java.rmi.registry.Registry"
							,"java.rmi.registry.RegistryHandler"
						)
						,"java.rmi.NotBoundException"
						,A("java.rmi.server"
							,"java.rmi.server.RMIClassLoaderSpi"
							,"java.rmi.server.SkeletonNotFoundException"
						)
					)
					,A("java.net"
						,"java.net.URLClassLoader"
						,"java.net.NetworkInterface"
					)
					,A("java.nio"
						,"java.nio.file.attribute.AclEntryType"
						,"java.nio.file.FileVisitResult"
					)
					,A("java.security"
						,"java.security.AccessController"
						,"java.security.AlgorithmParameters"
						,"java.security.cert.CertificateNotYetValidException"
						,"java.security.DrbgParameters.Reseed"
						,"java.security.PrivilegedAction"
						,"java.security.Provider"
						,"java.security.PublicKey"
						,"java.security.spec.PKCS8EncodedKeySpec"
					)
					,A("java.sql"
						,"java.sql.DriverManager"
						,"java.sql.Clob"
						,"java.sql.DriverManager.println"
						,"java.sql.Savepoint"
						,"java.sql.SQLType"
						,"javax.sql.StatementEventListener"/**2 spaces bef extends*/
					)
					,"java.text.CharacterIterator"
					,A("java.time"
						,"java.time.temporal.IsoFields"
						,A("java.time.temporal"
							,"java.time.temporal.ChronoUnit"
							,"java.time.temporal.ValueRange"
						)
						,"java.time.ZonedDateTime"
					)
					,A("java.util"//<editor-fold desc="">
						,"java.util.Base64"
						,A("java.util.concurrent"
							,"java.util.concurrent.CountedCompleter"
							,"java.util.concurrent.AbstractExecutorService"
							,"java.util.concurrent.CompletableFuture"
							,"java.util.concurrent.CompletionStage"
							,"java.util.concurrent.Delayed"
							,"java.util.concurrent.Executor"
							,"java.util.concurrent.ExecutorService"
							,"java.util.concurrent.ForkJoinPool.ManagedBlocker"
							,"java.util.concurrent.RecursiveTask"
							,"java.util.concurrent.RunnableFuture"
							,"java.util.concurrent.Semaphore"
						)
						,"java.util.AbstractQueue"
						,"java.util.Arrays"
						,"java.util.Deque"
						,"java.util.EventListener"
						,"java.util.EventListener"
						,"java.util.Enumeration"
						,"java.util.EventObject"
						,A("java.util.function"
							,"java.util.function.BiPredicate"
							,"java.util.function.BooleanSupplier"
							,"java.util.function.Consumer"
							,"java.util.function.DoublePredicate"
							,"java.util.function.Predicate"
							,"java.util.function.UnaryOperator"
						)
						,"java.util.HashMap"
						,"java.util.HashSet"
						,"java.util.Hashtable"
						,"java.util.IdentityHashMap"
						,"java.util.IllegalFormatCodePointException"
						,"java.util.LinkedHashSet"
						,"java.util.LinkedList"
						,"java.util.List"
						,"java.util.Locale"
						,"java.util.Map"
						,"java.util.NoSuchElementException"
						,"java.util.OptionalInt"
						,"java.util.Objects"
						,"java.util.PriorityQueue"
						,"java.util.Properties"
						,"java.util.ServiceLoader.Provider"
						,A("java.util.Spliterator"
							,"java.util.Spliterator.OfPrimitive"
						)
						,"java.util.SplittableRandom"
						,"java.util.Stack"
						,A("java.util.stream."
							,A("java.util.stream.DoubleStream"
								,"DoubleMapMultiConsumer"
							)
							,A("java.util.stream.Stream"
								,"java.util.stream.Stream.dropWhile"
							)
						)
						,"java.util.TooManyListenersException"
						,"java.util.Vector"
						,"java.util.WeakHashMap"
						,A("java.stream"
							,"java.util.stream.Stream"
							,"java.util.stream.StreamSupport"
						)
						,"java.util.zip.ZipEntry"
					)
					//</editor-fold>
				)
				//</editor-fold>
				,A("javax"//<editor-fold desc="">
					,"javax.accessibility.Accessible"
					,"javax.crypto.CipherSpi"
					,"javax.crypto.MacSpi"
					,A("javax.imageio"
						,A("javax.imageio.plugins.tiff.FaxTIFFTagSet"
							,"javax.imageio.plugins.tiff.FaxTIFFTagSet"
							,"javax.imageio.plugins.tiff.GeoTIFFTagSet"
						)
						,"javax.imageio.ImageTypeSpecifier"
						,A("javax.imageio.spi.ImageTranscoderSpi"
							,"javax.imageio.spi.ImageTranscoderSpi"
							,"javax.imageio.spi.RegisterableService"
						)
					)
					,"javax.lang.model.util.AbstractElementVisitor14"
					,"javax.lang.model.util.SimpleTypeVisitor6"
					,A("javax.management"
						,"javax.management.StandardEmitterMBean"
						,"javax.management.loading.PrivateClassLoader"
					)
					,A("javax.naming"
						,"javax.naming.Binding"
						,"javax.naming.InitialContext"
						,"javax.naming.ldap.HasControls"
						,A("javax.naming.spi"
							,"javax.naming.spi.NameAlreadyBoundException"
							,"javax.naming.spi.ResolveResult"
						)
					)
					,"javax.print.attribute.standard.EnumSyntax"
					,"javax.print.attribute.standard.Media"
					,A("javax.sound"
						,"javax.sound.sampled.spi.MixerProvider"
						,"javax.sound.sampled.FloatControl"
						,"javax.sound.sampled.Mixer"
					)
					,A("javax.swing"
						,"javax.swing.text.AsyncBoxView"
						,"javax.swing.Timer"
						,A("javax.swing.text.html.HTMLDocument"
							,"javax.swing.text.html.HTMLDocument.Iterator"
							,"javax.swing.text.html.HTMLDocument.LeafIterator"
						)
					)
					,"javax.lang.model.element.ModuleElement.RequiresDirective"
					,"javax.naming.spi.Resolver"
					,A("javax.print.attribute"
						,"javax.print.attribute.standard.RequestingUserName"
						,"javax.print.attribute.ResolutionSyntax"
					)
					,"javax.print.CancelablePrintJob"
					,"javax.tools.JavaFileObject"
					,"javax.imageio.plugins.jpeg.JPEGQTable"
					,A("javax.management"
						,"javax.management.ImmutableDescriptor"
						,"javax.management.JMException"
						,"javax.management.ListenerNotFoundException"
						,"javax.management.modelmbean.RequiredModelMBean"
						,"javax.management.OperationsException"
						,A("javax.management.relation"
							,"javax.management.relation.RelationException"
							,"javax.management.relation.RelationNotFoundException"
							,"javax.management.relation.RelationNotification"
							,"javax.management.relation.RelationServiceNotRegisteredException"
						)
					)
					,A("javax.naming"
						,A("javax.naming.ldap"
							,"javax.naming.ldap.HasControls"
							,"javax.naming.ldap.LdapName"
						)
						,"javax.naming.Name"
						,"javax.naming.NamingException"
						,"javax.naming.NoInitialContextException"
					)
					,"javax.net.ssl.HandshakeCompletedEvent"
					,"javax.print.attribute.standard.PrinterURI"
					,A("javax.swing"
						,"javax.swing.AbstractAction"
						,"javax.swing.AbstractFormatter"
						,"javax.swing.BorderFactory"
						,"javax.swing.JFrame.isDefaultLookAndFeelDecorated"
						/***/,"javax.swing.JProgressBar"
						/***/,"javax.swing.JRadioButtonMenuItem"
						/***/,"javax.swing.JRootPane"
						,"javax.swing.JSeparator"
						,"javax.swing.JToggleButton"
						,"javax.swing.JFormattedTextField"
						,"javax.swing.LookAndFeel"
						,A("javax.swing.plaf"
							,"javax.swing.plaf.basic.BasicInternalFrameTitlePane.RestoreAction"
							,"javax.swing.plaf.basic.BasicLookAndFeel"
							,"javax.swing.plaf.nimbus.NimbusLookAndFeel"
							,A("javax.swing.plaf.synth"
								,"javax.swing.plaf.synth.SynthLookAndFeel"
								,"javax.swing.plaf.synth.SynthRadioButtonMenuItemUI"
							)
						)
						,"javax.swing.table.TableRowSorter"
						,A("javax.swing.text.html"
							,"javax.swing.text.html.ImageView"
							,A("javax.swing.text.html.parser"
								,"javax.swing.text.html.parser.DTDConstants"
								,"javax.swing.text.html.parser.Entity"
							)
						)
					)
					,A("javax.tools"
						,"javax.tools.FileObject"
						,"javax.tools.ForwardingJavaFileObject"
						,"javax.tools.JavaFileObject"
						,"javax.tools.JavaFileManager"
						,"javax.tools.OptionChecker"
						,"javax.tools.StandardJavaFileManager"
					)
					,A("javax.naming"
						,"javax.naming.PartialResultException"
						,"javax.naming.MalformedLinkException"
					)
					,"javax.crypto.spec.ChaCha20ParameterSpec"
					,"javax.print.attribute.HashPrintServiceAttributeSet"
					,A("javax.management"
						,A("javax.management.loading"
							,"javax.management.loading.MLet"
							,"javax.management.loading.ClassLoaderRepository"
						)
						,"javax.management.MalformedObjectNameException"/*Extra line break above package statement. 3 spaces between, parent, & body start.*/
						,"javax.management.ObjectName.PlatformManagedObject"
						,"javax.management.relation.Relation"
					)
					,"javax.print.attribute.standard.MediaSize.ISO"
					,"javax.script.Compilable"
					,A("javax.security.auth"
						,"javax.security.auth.callback.CallbackHandler"
						,"javax.security.auth.kerbero.KerberosPrincipal"
						,A("javax.security.auth.Refreshable"
							,"javax.security.auth.Refreshable.isCurrent"
						)
						,"javax.security.auth.x500.X500Principal"
					)
					,A("javax.xml.crypto"
						,A("javax.xml.crypto"
							,"javax.xml.crypto.KeySelector.Purpose"
							,"javax.xml.crypto.dsig.DigestMethod"
							,"javax.xml.crypto.dsig.keyinfo.RetrievalMethod"
							,"javax.xml.crypto.URIReference"
							,"javax.xml.crypto.XMLStructure"
						)
						,"javax.xml.transform.Result"
					)
				)
				//</editor-fold>
				,A("jdk"//<editor-fold desc="">
					,A("dynalink.linker"
						,"jdk.dynalink.linker.GuardingDynamicLinker"
						,"jdk.dynalink.linker.TypeBasedGuardingDynamicLinker"
					)
					,A("jdk.incubator.foreign"
						,"CLinker"
						,"jdk.incubator.foreign.MemoryAccess"
						,A("jdk.incubator.vector"
							,"jdk.incubator.vector.FloatVector"
							,"jdk.incubator.vector.VectorOperators"
							,"jdk.incubator.vector.VectorOperators.Conversion"
							,"jdk.incubator.vector.VectorOperators.Operator"
							,"jdk.incubator.vector.VectorOperators.Test"
						)
					)
					,A("jdk.internal"
						,"misc.CDS"
						,"misc.VM.BufferPool"
						,A("org"
							,"jdk.internal.org.jline.utils.AttributedStyle"
							,A("jdk.internal.org.objectweb.asm"
								,"jdk.internal.org.objectweb.asm.ClassVisitor"
								,A("jdk.internal.org.objectweb.asm.commons"
									,"jdk.internal.org.objectweb.asm.commons.ClassRemapper"
									,A("jdk.internal.org.objectweb.asm.commons.Method"
										,"jdk.internal.org.objectweb.asm.commons.Method.getMethod"
									)
									,"jdk.internal.org.objectweb.asm.commons.RemappingClassAdapter"
									,"jdk.internal.org.objectweb.asm.commons.RemappingSignatureAdapter"
									,"jdk.internal.org.objectweb.asm.commons.StaticInitMerger"
								)
								,"jdk.internal.org.objectweb.asm.Type"
							)
							,A("jdk.internal.reflect"
								,"jdk.internal.reflect.Reflection.getCallerClass"
								,A("jdk.internal.reflect.ReflectionFactory"
									,"jdk.internal.reflect.ReflectionFactory.GetReflectionFactoryAction"
								)
								,"jdk.internal.reflect.CallerSensitive"
								,"jdk.internal.reflect.ReflectionFactory.setConstructorAccessor"
							)
						)
					)
					,A("jdk.jfr"
						,"MemoryAddress"
						,"Frequency"
						,"Registered"
					)
					,A("jdk.dynalink"
						,A("linker"
							,"jdk.dynalink.linker.support.CompositeTypeBasedGuardingDynamicLinker"
							,"jdk.dynalink.linker.TypeBasedGuardingDynamicLinker"
						)
						,"Namespace"
						,"StandardNamespace"
					)
					,A("jdk.internal"
						,"jdk.internal.org.objectweb.asm.commons.StaticInitMerger"
						,"misc.CDS"
					)
					,"jdk.dynalink.beans.StaticClass"
					,"jdk.jfr.Description"
					,"jdk.incubator.foreign.MemoryAddress"
					,A("jdk.jshell"
						,"DeclarationSnippet"
						,"GeneralWrap"
						,"ImportSnippet"
						,"PersistentSnippet"
						,"jdk.jshell.SourceCodeAnalysis.CompletionInfo"
						,A("jdk.jshell.spi"
							,A("jdk.jshell.spi.ExecutionControl"
								,"jdk.jshell.spi.ExecutionControl.ClassBytecodes"
								,"jdk.jshell.spi.ExecutionControl.ClassInstallException"
							)
							,"jdk.jshell.spi.ExecutionControlException"
						)
						,"jdk.jshell.Snippet.Kind"
						,"jdk.jshell.spi.ExecutionControl"
						,"jdk.jshell.spi.ExecutionControl.ClassInstallException"
						,"jdk.jshell.spi.ExecutionControl.ExecutionControlException"
						,"jdk.jshell.StatementSnippet"
						,"jdk.jshell.TypeDeclSnippet"
						,"jdk.jshell.Wrap"
					)
				)//</editor-fold>
				,A("netscape.javascript"
					,"JSObject"
					,"JSException"
				)
				,A("org"//<editor-fold desc="org">
					,"org.ietf.jgss.GSSName"
					,A("intellij.lang.annotations"
						,"org.intellij.lang.annotations.Identifier"
						,"org.intellij.lang.annotations.MagicConstant"
						,"org.intellij.lang.annotations.RegExp"
					)
					,A("org.jetbrains.annotations"
						,A("org.jetbrains.annotations.ApiStatus"
							,"org.jetbrains.annotations.ApiStatus.AvailableSince"
							,"org.jetbrains.annotations.NonNls"
						)
						,"org.jetbrains.annotations.Nullable"
					)
					,A("org.w3c.dom"
						,"org.w3c.dom.Entity"
						,"org.w3c.dom.traversal.TreeWalker"
						,"org.w3c.dom.Node"
						,"org.w3c.dom.traversal.NodeIterator"
					)
					,"org.xml.sax.Parser"
				)
				//</editor-fold>
				,A("sun"
					,A("sun.awt"
						,"sun.awt.image.BytePackedRaster"
						,A("sun.awt.image.PixelConverter"
							,"sun.awt.image.PixelConverter.Bgrx"
						)
						,"sun.awt.image.SunWritableRaster"
					)
					,"sun.util.logging.PlatformLogger.getLogger"
				)
			}
		);
	}
}